name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

    
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on
permissions:
  contents: write

jobs:
  deploy:
    name: 将更新后的文件重新编译并推送到分支
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4
        
      - name: checkout
        uses: actions/setup-node@v4
        
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build website
        run: yarn build

      - name: compressor
        run: tar -czvf K230.tar.gz ./build
      # - name: compressor
      #   run: scp -P 12999 ./K230.tar.gz lio@219.135.168.174:/home/lio/k230
        
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     password: ${{ secrets.POSSWORD }}
      #     port: ${{ secrets.PORT }}
      - name: 通过 ssh 密码复制文件
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.POSSWORD }}
          port: ${{ secrets.PORT }}
          source: "./K230.tar.gz"
          target: /home/lio/k230
      # - name: compressor
      #   run: ${{ secrets.POSSWORD }}

        
      # - name: 安装npm
      #   run: curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      # - name: 安装node.js
      #   run: sudo apt-get install -y nodejs
      # - name: Build website
      #   run: npm run build
      
      # - name: 推送到服务器
      #   run: scp -r /root/lk root@43.224.34.73:/home/lk/cpfile
        
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.TOKEN }}
      #     # Build output to publish to the `gh-pages` branch:
      #     publish_dir: ./build
      #     cname: aiyouhui.site
          
  download_test:
    needs: deploy
    
    name: 更新服务器文件
    runs-on: ubuntu-latest
    steps:
      # 下载build文件到服务器
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.POSSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/lio/k230
            rm -rf ./K230
            
            tar -xzvf K230.tar.gz
            mv build K230
            # git clone -b gh-pages https://github.com/tm330075395/K230.git

